"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var calculator_1 = require("./calculator");
console.log("Operaciones matemáticas con TypeScript");
console.log("Sumar 53 + 31 = ", (0, calculator_1.suma)(53, 31));
console.log("Restar 86 - 43 = ", (0, calculator_1.resta)(86, 43));
console.log("Multiplicar 1024 * 16 = ", (0, calculator_1.multiplicacion)(1024, 16));
console.log("Dividir 1960 / 2 = ", (0, calculator_1.division)(1960, 2));
//console.log("Dividir 100 / 0 = ", division(100, 0));
console.log("Valor de Pi = ", calculator_1.Pi);
console.log("Multiplicar Pi * 360 = ", (0, calculator_1.multiplicacion)(calculator_1.Pi, 360));
