"use strict";
let nombre = "Leo";
let edad = 37;
let esDesarrollador = true;
let mes;
let variableNull = null;
console.log(`hola, ${nombre}`);
console.log('Mes inicial: ', mes);
mes = 'Julio';
console.log('Mes actualizado: ', mes);
